name: fortiweb-autoscale
on:
        push:
                tags:
                        - 'v1.0.8-beta'
                branches:
                        - main
jobs:
        build:
                name: Upload New Release
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Use Node.js
                          uses: actions/setup-node@v1
                          with:
                            node-version: '12.x'
                        - run: npm install
                        - run: npm run Build
                        - name: Checkout Code
                          uses: actions/checkout@v2
                        - name: Build Project
                          run: zip -r release.zip . -x ".git/*" "./github/*" ".gitignore"
                        - name: Create Release
                          id: create_release
                          run: |
                            set -x
                            assets=()
                            for asset in ./dist/*.zip; do
                              assets+=("-a" "$asset")
                            done
                            hub release create "${assets[@]}" -m "1.0.8-beta" "fortiweb-autoscale-ver-108"
                          env:
                                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
