name: fortiweb-autoscale
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: create-fortiweb-autoscale-assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '8.11.1'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - run: npm install
      - run: npm run build
      - name: create-fortiweb-autoscale-release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: ./dist/*
          tag: ${{github.ref}}
          overwrite: true
          body: "FortiWeb Autoscale Release"
          file_glob: true
